// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmTbKx9g5Qdu7FT5fO-ffvnCTqG6DldbM',
    appId: '1:436857713952:web:6fc25e3e3ea94118035345',
    messagingSenderId: '436857713952',
    projectId: 'chatappf-90eb9',
    authDomain: 'chatappf-90eb9.firebaseapp.com',
    storageBucket: 'chatappf-90eb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZRnbrJcvcIa5UvBWb8ZhR_H1izjLwCs',
    appId: '1:436857713952:android:2aabff5411f1ed80035345',
    messagingSenderId: '436857713952',
    projectId: 'chatappf-90eb9',
    storageBucket: 'chatappf-90eb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ1XbPBCdT8pVWJ2jMtshC7GDvSSyla5s',
    appId: '1:436857713952:ios:92bef14431889ff0035345',
    messagingSenderId: '436857713952',
    projectId: 'chatappf-90eb9',
    storageBucket: 'chatappf-90eb9.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ1XbPBCdT8pVWJ2jMtshC7GDvSSyla5s',
    appId: '1:436857713952:ios:92bef14431889ff0035345',
    messagingSenderId: '436857713952',
    projectId: 'chatappf-90eb9',
    storageBucket: 'chatappf-90eb9.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmTbKx9g5Qdu7FT5fO-ffvnCTqG6DldbM',
    appId: '1:436857713952:web:fbe28de301142b66035345',
    messagingSenderId: '436857713952',
    projectId: 'chatappf-90eb9',
    authDomain: 'chatappf-90eb9.firebaseapp.com',
    storageBucket: 'chatappf-90eb9.appspot.com',
  );
}
